### ISSUE TITLE
An error was encountered while trying to load plugin

### ISSUE THREAD

**Issue by U5KUN** [riolubruh/SplitLargeFiles#11]
An error was encountered while trying to load this plugin.

![スクリーンショット 2024-07-01 18 06 41](https://github.com/riolubruh/SplitLargeFiles/assets/87700116/f0f70184-1ac7-4328-90d7-f04b4cfd3f4c)

```
[BetterDiscord] [WebpackModules~getModule] Module filter threw an exception. (m) => Object.values(m).filter((v) => v?.toString).map((v) => v.toString()).some((v) => v.includes("getCurrentUser();") && v.includes("getUserMaxFileSize")) TypeError: Method %TypedArray%.prototype.join called on incompatible receiver [object Object]
    at Object.join (<anonymous>)
    at Object.toString (<anonymous>)
    at eval (SplitLargeFiles.plugin.js:103:106)
    at Array.map (<anonymous>)
    at eval (SplitLargeFiles.plugin.js:103:93)
    at renderer.js:5:44244
    at l.getModule (renderer.js:5:45543)
    at Object.getModule (renderer.js:5:417163)
    at plugin (SplitLargeFiles.plugin.js:103:32)
    at eval (SplitLargeFiles.plugin.js:733:13)
    at eval (SplitLargeFiles.plugin.js:734:3)
    at N.requireAddon (renderer.js:5:28601)
    at N.loadAddon (renderer.js:5:6221)
    at N.loadAddon (renderer.js:5:26269)
    at renderer.js:5:4201
```

macOS Sonoma 14.0
Discord Canary 0.0.546 (0.0.546)
BetterDiscord v1.10.2

**Comment by ffuentesm** [comment]
Same problem. 
Plugin needs to update for the BD changes.
